language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.5
notifications:
    email: false
addons:
    apt:
        packages:
            - python3-sphinx
            - libevent-dev
cache:
    - pip
    - directories:
          - kotekan

services:
    - docker

before_install:
    - pip install pycodestyle
    - pip install pydocstyle

install:
    - pip install .

script:
    # Run pycodestyle on all .py files in all subfolders
    - find . -name \*.py ! -name versioneer.py -exec pycodestyle --max-line-length=99 {} +

    # Run pydocstyle on all .py files
    - find . -name \*.py ! -name versioneer.py ! -name conf.py ! -name _version.py -exec pydocstyle --convention=numpy {} +

    # Build docs
    - cd docs
    - make html

    # Build kotekan (cached repository)
    - if cd kotekan; then git pull; else git clone --single-branch --branch master https://github.com/kotekan/kotekan.git; fi
    - cd kotekan/build
    - cmake ..
    - make -j 4

    # Simulate CHIME cluster
    - cd ../../tests/simulate-chime
    - docker-compose -f docker-compose.yaml up
