language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.5
notifications:
    email: false
addons:
    apt:
        packages:
            - python3-sphinx
            - libevent-dev

before_install:
    - pip install pycodestyle
    - pip install pydocstyle

install:
    - pip install .

script:
    # Run pycodestyle on all .py files in all subfolders
    - find . -name \*.py ! -name versioneer.py -exec pycodestyle --max-line-length=99 {} +

    # Run pydocstyle on all .py files
    - find . -name \*.py ! -name versioneer.py ! -name conf.py ! -name _version.py -exec pydocstyle --convention=numpy {} +

    # Build docs
    - cd docs
    - make html

    # Install kotekan
    - git clone --single-branch --branch master git@github.com:kotekan/kotekan.git
    - cd kotekan/build
    - cmake ..
    - make -j 4
    - sudo make install
    - cd ../..
