language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.5
notifications:
    email: false

before_install:
    - pip install pycodestyle
    - pip install pydocstyle

install:
    - pip install .

script:
    # Run pycodestyle on all .py files in all subfolders
    - find . -name \*.py -exec pycodestyle --max-line-length=99 {} +

    # Run pydocstyle on all .py files
    - find . -name \*.py -exec pydocstyle --convention=numpy {} +

    # Build docs
    - cd docs
    - make html
